const posts = [
  {
    slug: 'breaking:-"unity-accord"-signed,-dashing-hopes-for-immediate-separatist-resolution-in-atheria',
    title: 'BREAKING: "Unity Accord" Signed, Dashing Hopes for Immediate Separatist Resolution in Atheria',
    excerpt: 'Tensions remain high as the \'Unity Accord\' between the Atherian central government and the Northern Provinces was inked today, a move critics argue consolidates existing power structures and sidelines genuine self-determination demands.',
    date: '2026-04-12',
    body: 'The Atherian capital, Veridia, buzzed with a mix of relief and apprehension today as President Anya Sharma and representatives from the secessionist Northern Provinces, led by Governor Silas Vance, formally signed the "Unity Accord." The hastily arranged ceremony, broadcast live globally, was hailed by the government as a "historic step towards national reconciliation." However, for many within the Northern Provinces, particularly those advocating for full independence, the Accord represents a significant setback.  Sources close to the separatist movement reveal deep divisions over the terms, which reportedly offer increased regional autonomy but fall far short of the sovereignty demanded.  Critics point to the inclusion of clauses that maintain significant central government oversight on key economic and defense matters, effectively preserving Atheria\'s territorial integrity at the expense of true self-governance.  International observers expressed cautious optimism, but many fear the Accord may only serve to suppress underlying grievances, potentially fueling future unrest rather than resolving it.  The signing followed a turbulent week of negotiations in Veridia, marked by protests and sporadic clashes between government forces and regional militia remnants. The full details of the Accord are expected to be released within 24 hours, but preliminary reports suggest it is a compromise that satisfies neither the hardline unionists nor the ardent separatists, leaving the future of Atheria shrouded in uncertainty.',
    url: '/posts/breaking:-"unity-accord"-signed,-dashing-hopes-for-immediate-separatist-resolution-in-atheria.html'
  }
];